# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e0e024df564834b3a5614da72a11036ffde7714e13717a55872499cf46856e619043f8856b5222adfc66ac32edfa5f9b644baf6a7164df844d8ea1872af47c

test:
  secret_key_base: c62c28cea48f61428bd976f48d34dd3f23006e6119dc88383de463d2ced8ff8387d143c36e4b9af78618aaf51f665cde2690a8569da58e0d52bddc21329f3723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
